language: ruby
rvm:
  - 2.1.1
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis'
  - bundle exec rake bower:install
  - bundle exec rake db:seed
