default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: census_development

test:
  <<: *default
  database: census_test

production:
  <<: *default
  database: census_production
  username: census
  password: <%= ENV['CENSUS_DATABASE_PASSWORD'] %>
